name: A small workflow template to test how well this works.

on: 
  push:
    branches:
    - $default-branch

jobs:
  runs-on: ubuntu-latest
  steps: 
    - name: do a thing
      run: echo "thing was done!"
